image:
  tag: 0.0.80
  repository: ghcr.io/jenkins-x/jx-kh-check
example:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/example
  runInterval: 30s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
jxWebhooks:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-webhooks
  runInterval: 90s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
jxWebhookEvents:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-webhook-events
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
jxInstall:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-install
  runInterval: 90s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
jxBotToken:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-bot-token
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  gitProvider:
jxPodStatus:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-pod-status
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 15m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  cluster:
    enabled: false
# the upstream uses a check indentation so keeping it here for this check so we dont need to change the helm template
# When enabled equals to true, runAsUser and fsGroup will be
# included to all khchecks as specified below.
securityContext:
  enabled: true # if enabled is set to false, securityContext settings will not be applied at all in checker pod custom resources
  runAsNonRoot: true
  runAsUser: 999
  fsGroup: 999
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
check:
  podRestarts:
    enabled: false
    runInterval: 5m
    timeout: 10m
    image:
      repository: ghcr.io/jenkins-x/pod-restarts-check
    allNamespaces: true
    extraEnvs:
      MAX_FAILURES_ALLOWED: "10"
    nodeSelector: {}
    tolerations: []
    #- key: "key"
    #  operator: "Equal"
    #  value: "value"
    #  effect: "NoSchedule"
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
jxSecrets:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-secrets
  runInterval: 60s # The interval that Kuberhealthy will run your check on
  timeout: 5m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  cluster:
    enabled: false
